/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromptsIndexRouteImport } from './routes/prompts/index'
import { Route as PromptsPromptIdRouteImport } from './routes/prompts/$promptId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsIndexRoute = PromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsPromptIdRoute = PromptsPromptIdRouteImport.update({
  id: '/prompts/$promptId',
  path: '/prompts/$promptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/prompts/$promptId': typeof PromptsPromptIdRoute
  '/prompts/': typeof PromptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/prompts/$promptId': typeof PromptsPromptIdRoute
  '/prompts': typeof PromptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/prompts/$promptId': typeof PromptsPromptIdRoute
  '/prompts/': typeof PromptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/settings' | '/prompts/$promptId' | '/prompts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/settings' | '/prompts/$promptId' | '/prompts'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/prompts/$promptId'
    | '/prompts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  PromptsPromptIdRoute: typeof PromptsPromptIdRoute
  PromptsIndexRoute: typeof PromptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/': {
      id: '/prompts/'
      path: '/prompts'
      fullPath: '/prompts/'
      preLoaderRoute: typeof PromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$promptId': {
      id: '/prompts/$promptId'
      path: '/prompts/$promptId'
      fullPath: '/prompts/$promptId'
      preLoaderRoute: typeof PromptsPromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  PromptsPromptIdRoute: PromptsPromptIdRoute,
  PromptsIndexRoute: PromptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
